all:
  name: ▶ Build All ◀
  dependencies:
    - .yamato/Build.yml#build_linux
    - .yamato/Build.yml#build_windows
    - .yamato/Build.yml#build_osx_universal
    - .yamato/Build.yml#check_generated_code

build_linux:
  name: Build - Linux
  agent:
    type: Unity::VM
    image: platform-foundation/linux-ubuntu-18.04-mono-bokken:0.1.7-978398
    flavor: b1.xlarge
    config:
      env_vars:
        - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
  commands:
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
  timeout: 30
  artifacts:
    reported_artifacts:
      paths:
        - flatc

build_windows:
  name: Build - Windows
  agent:
    type: Unity::VM
    image: burst/burst-base:1.0.8-1195360
    flavor: b1.xlarge
  commands:
    - cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
  timeout: 30
  artifacts:
    reported_artifacts:
      paths:
        - Release\flatc.exe

build_osx_universal:
  name: Build - OSX - universal
  agent:
    type: Unity::VM::osx
    image: slough-ops/macos-15-xcode:v2.0.20
    flavor: m1.mac
  commands:
    - brew install cmake
    - cmake -G "Xcode" -DFLATBUFFERS_BUILD_TESTS=0 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - lipo -info Release/flatc
  timeout: 30
  artifacts:
    reported_artifacts:
      paths:
        - Release/flatc

check_generated_code:
  name: Check - Generated Code
  agent:
    type: Unity::VM
    image: platform-foundation/linux-ubuntu-18.04-mono-bokken:0.1.7-978398
    flavor: b1.xlarge
    config:
      env_vars:
        - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
  commands:
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_BUILD_TESTS=OFF
    - cmake --build . --config Release
    - python3 scripts/check_generate_code.py
    - python3 scripts/check-grpc-generated-code.py
  timeout: 30
